### ISSUE TITLE
Use travis-ci (or some other solution) to run tests

### ISSUE THREAD

**Issue by pipermerriam** [jmurty/xml4h#11]
As someone contributing a pull request, it would be nice to know that all of the tests on my PR are passing.

I also imagine that as someone reviewing pull requests it would also be nice to know that tests are passing.

http://docs.travis-ci.com/user/getting-started/

travis-ci is pretty easy to setup.  Here is an example `.travis.yml` file from another project that I use travis for.  https://github.com/Apogaea/ladder/blob/master/.travis.yml

**Comment by pipermerriam** [comment]
Let me know if this is something you're ok with and I'll get a PR in for it.  The maintainers of this project will still have to enable the tests runs on travis-ci though.

**Comment by jmurty** [comment]
Thanks for the request and links, I have now set up Travis CI integration for this project.

While testing this I also came across and fixed a subtle bug which was causing intermittent Tox test build failures, so yeah, more testing is always good...
