### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by pipermerriam** [jmurty/xml4h#9]
It would be great to have python 3 support for this library.

**Comment by jmurty** [comment]
I agree! 

I made a brief attempt at this a long, long time ago but abandoned it before I got anywhere useful. It would be awesome if you could make this happen, let me know if I can help and I'll do what I can.

**Comment by jmurty** [comment]
Python3 support is now available in version 1.0: https://pypi.org/project/xml4h/1.0/
